"""Refactor enums to int id plus str name columns

Revision ID: 2dc9d889793e
Revises: c8a0244e1802
Create Date: 2026-03-07 08:18:29.864951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2dc9d889793e'
down_revision: Union[str, None] = 'c8a0244e1802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_tier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'subscription_tier_name')
    op.drop_column('users', 'subscription_tier_id')
    # ### end Alembic commands ###