"""Add is_default to person model and make birth fields nullable

Revision ID: 877046abc1fb
Revises: ff61acc93b5e
Create Date: 2026-03-24 00:23:06.786978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '877046abc1fb'
down_revision: Union[str, None] = 'ff61acc93b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('person', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('person', 'time_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('person', 'place_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    op.alter_column('person', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    op.alter_column('person', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('person', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    op.alter_column('person', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    op.alter_column('person', 'place_of_birth',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('person', 'time_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('person', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('person', 'is_default')
    # ### end Alembic commands ###