"""add remedy_progress table and user ethnicity field

Revision ID: 928de2f7e09f
Revises: 877046abc1fb
Create Date: 2026-04-03 19:21:05.892583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '928de2f7e09f'
down_revision: Union[str, None] = '877046abc1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remedy_progress',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('remedy_progress_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('remedy_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remedy_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('remedy_progress_id')
    )
    op.create_index(op.f('ix_remedy_progress_organization_id'), 'remedy_progress', ['organization_id'], unique=False)
    op.create_index(op.f('ix_remedy_progress_person_id'), 'remedy_progress', ['person_id'], unique=False)
    op.create_index(op.f('ix_remedy_progress_user_id'), 'remedy_progress', ['user_id'], unique=False)
    op.add_column('users', sa.Column('ethnicity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ethnicity')
    op.drop_index(op.f('ix_remedy_progress_user_id'), table_name='remedy_progress')
    op.drop_index(op.f('ix_remedy_progress_person_id'), table_name='remedy_progress')
    op.drop_index(op.f('ix_remedy_progress_organization_id'), table_name='remedy_progress')
    op.drop_table('remedy_progress')
    # ### end Alembic commands ###