"""add_language_preference_to_users

Revision ID: a572be426447
Revises: 928de2f7e09f
Create Date: 2026-04-07 19:29:14.320190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a572be426447'
down_revision: Union[str, None] = '928de2f7e09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_preference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_preference')
    # ### end Alembic commands ###