"""Add user_id to tenant models make organization_id nullable

Revision ID: ff61acc93b5e
Revises: 27e499bd60ad
Create Date: 2026-03-23 10:02:16.424256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff61acc93b5e'
down_revision: Union[str, None] = '27e499bd60ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('astrology_chart', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('astrology_chart', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_astrology_chart_user_id'), 'astrology_chart', ['user_id'], unique=False)
    op.create_foreign_key(None, 'astrology_chart', 'users', ['user_id'], ['user_id'])
    op.add_column('chart_interpretation', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('chart_interpretation', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_chart_interpretation_user_id'), 'chart_interpretation', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chart_interpretation', 'users', ['user_id'], ['user_id'])
    op.add_column('interpretation_embedding', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('interpretation_embedding', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_interpretation_embedding_user_id'), 'interpretation_embedding', ['user_id'], unique=False)
    op.create_foreign_key(None, 'interpretation_embedding', 'users', ['user_id'], ['user_id'])
    op.add_column('person', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('person', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_person_user_id'), 'person', ['user_id'], unique=False)
    op.create_foreign_key(None, 'person', 'users', ['user_id'], ['user_id'])
    op.add_column('planet_position', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.alter_column('planet_position', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_planet_position_user_id'), 'planet_position', ['user_id'], unique=False)
    op.create_foreign_key(None, 'planet_position', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet_position', type_='foreignkey')
    op.drop_index(op.f('ix_planet_position_user_id'), table_name='planet_position')
    op.alter_column('planet_position', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('planet_position', 'user_id')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_index(op.f('ix_person_user_id'), table_name='person')
    op.alter_column('person', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('person', 'user_id')
    op.drop_constraint(None, 'interpretation_embedding', type_='foreignkey')
    op.drop_index(op.f('ix_interpretation_embedding_user_id'), table_name='interpretation_embedding')
    op.alter_column('interpretation_embedding', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('interpretation_embedding', 'user_id')
    op.drop_constraint(None, 'chart_interpretation', type_='foreignkey')
    op.drop_index(op.f('ix_chart_interpretation_user_id'), table_name='chart_interpretation')
    op.alter_column('chart_interpretation', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chart_interpretation', 'user_id')
    op.drop_constraint(None, 'astrology_chart', type_='foreignkey')
    op.drop_index(op.f('ix_astrology_chart_user_id'), table_name='astrology_chart')
    op.alter_column('astrology_chart', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('astrology_chart', 'user_id')
    # ### end Alembic commands ###