/**
 * Comprehensive astrology glossary with translations in 8 languages.
 *
 * Keys are lowercase English terms. Each entry provides the canonical English
 * name plus accurate Unicode translations in Tamil (ta), Telugu (te),
 * Kannada (kn), Hindi (hi), Malayalam (ml), Bengali (bn), and Sanskrit (sa).
 *
 * When a native-script form is identical to the Sanskrit/Devanagari, that is
 * intentional (many Indic languages borrow Sanskritic forms directly).
 */

export type GlossaryLang = 'en' | 'ta' | 'te' | 'kn' | 'hi' | 'ml' | 'bn' | 'sa';

export interface GlossaryEntry {
  en: string;
  ta: string;
  te: string;
  kn: string;
  hi: string;
  ml: string;
  bn: string;
  sa: string;
}

export const GLOSSARY: Record<string, GlossaryEntry> = {
  // ===========================================================================
  // 27 Nakshatras
  // ===========================================================================
  ashwini: {
    en: 'Ashwini',
    ta: 'அஸ்வினி',
    te: 'అశ్విని',
    kn: 'ಅಶ್ವಿನಿ',
    hi: 'अश्विनी',
    ml: 'അശ്വതി',
    bn: 'অশ্বিনী',
    sa: 'अश्विनी',
  },
  bharani: {
    en: 'Bharani',
    ta: 'பரணி',
    te: 'భరణి',
    kn: 'ಭರಣಿ',
    hi: 'भरणी',
    ml: 'ഭരണി',
    bn: 'ভরণী',
    sa: 'भरणी',
  },
  krittika: {
    en: 'Krittika',
    ta: 'கிருத்திகை',
    te: 'కృత్తిక',
    kn: 'ಕೃತ್ತಿಕಾ',
    hi: 'कृत्तिका',
    ml: 'കാര്‍ത്തിക',
    bn: 'কৃত্তিকা',
    sa: 'कृत्तिका',
  },
  rohini: {
    en: 'Rohini',
    ta: 'ரோகிணி',
    te: 'రోహిణి',
    kn: 'ರೋಹಿಣಿ',
    hi: 'रोहिणी',
    ml: 'രോഹിണി',
    bn: 'রোহিণী',
    sa: 'रोहिणी',
  },
  mrigashira: {
    en: 'Mrigashira',
    ta: 'மிருகசீரிடம்',
    te: 'మృగశిర',
    kn: 'ಮೃಗಶಿರಾ',
    hi: 'मृगशिरा',
    ml: 'മകയിരം',
    bn: 'মৃগশিরা',
    sa: 'मृगशिरा',
  },
  ardra: {
    en: 'Ardra',
    ta: 'திருவாதிரை',
    te: 'ఆర్ద్ర',
    kn: 'ಆರ್ದ್ರಾ',
    hi: 'आर्द्रा',
    ml: 'തിരുവാതിര',
    bn: 'আর্দ্রা',
    sa: 'आर्द्रा',
  },
  punarvasu: {
    en: 'Punarvasu',
    ta: 'புனர்பூசம்',
    te: 'పునర్వసు',
    kn: 'ಪುನರ್ವಸು',
    hi: 'पुनर्वसु',
    ml: 'പുണര്‍തം',
    bn: 'পুনর্বসু',
    sa: 'पुनर्वसु',
  },
  pushya: {
    en: 'Pushya',
    ta: 'பூசம்',
    te: 'పుష్యమి',
    kn: 'ಪುಷ್ಯ',
    hi: 'पुष्य',
    ml: 'പൂയം',
    bn: 'পুষ্য',
    sa: 'पुष्य',
  },
  ashlesha: {
    en: 'Ashlesha',
    ta: 'ஆயில்யம்',
    te: 'ఆశ్లేష',
    kn: 'ಆಶ್ಲೇಷಾ',
    hi: 'आश्लेषा',
    ml: 'ആയില്യം',
    bn: 'আশ্লেষা',
    sa: 'आश्लेषा',
  },
  magha: {
    en: 'Magha',
    ta: 'மகம்',
    te: 'మఘ',
    kn: 'ಮಘಾ',
    hi: 'मघा',
    ml: 'മകം',
    bn: 'মঘা',
    sa: 'मघा',
  },
  'purva phalguni': {
    en: 'Purva Phalguni',
    ta: 'பூரம்',
    te: 'పూర్వ ఫల్గుణి',
    kn: 'ಪೂರ್ವ ಫಲ್ಗುಣಿ',
    hi: 'पूर्व फाल्गुनी',
    ml: 'പൂരം',
    bn: 'পূর্ব ফাল্গুনী',
    sa: 'पूर्वफाल्गुनी',
  },
  'uttara phalguni': {
    en: 'Uttara Phalguni',
    ta: 'உத்திரம்',
    te: 'ఉత్తర ఫల్గుణి',
    kn: 'ಉತ್ತರ ಫಲ್ಗುಣಿ',
    hi: 'उत्तर फाल्गुनी',
    ml: 'ഉത്രം',
    bn: 'উত্তর ফাল্গুনী',
    sa: 'उत्तरफाल्गुनी',
  },
  hasta: {
    en: 'Hasta',
    ta: 'அஸ்தம்',
    te: 'హస్త',
    kn: 'ಹಸ್ತ',
    hi: 'हस्त',
    ml: 'അത്തം',
    bn: 'হস্ত',
    sa: 'हस्त',
  },
  chitra: {
    en: 'Chitra',
    ta: 'சித்திரை',
    te: 'చిత్ర',
    kn: 'ಚಿತ್ರಾ',
    hi: 'चित्रा',
    ml: 'ചിത്തിര',
    bn: 'চিত্রা',
    sa: 'चित्रा',
  },
  swati: {
    en: 'Swati',
    ta: 'சுவாதி',
    te: 'స్వాతి',
    kn: 'ಸ್ವಾತಿ',
    hi: 'स्वाति',
    ml: 'ചോതി',
    bn: 'স্বাতী',
    sa: 'स्वाती',
  },
  vishakha: {
    en: 'Vishakha',
    ta: 'விசாகம்',
    te: 'విశాఖ',
    kn: 'ವಿಶಾಖ',
    hi: 'विशाखा',
    ml: 'വിശാഖം',
    bn: 'বিশাখা',
    sa: 'विशाखा',
  },
  anuradha: {
    en: 'Anuradha',
    ta: 'அனுஷம்',
    te: 'అనురాధ',
    kn: 'ಅನುರಾಧ',
    hi: 'अनुराधा',
    ml: 'അനിഴം',
    bn: 'অনুরাধা',
    sa: 'अनुराधा',
  },
  jyeshtha: {
    en: 'Jyeshtha',
    ta: 'கேட்டை',
    te: 'జ్యేష్ఠ',
    kn: 'ಜ್ಯೇಷ್ಠ',
    hi: 'ज्येष्ठा',
    ml: 'തൃക്കേട്ട',
    bn: 'জ্যেষ্ঠা',
    sa: 'ज्येष्ठा',
  },
  mula: {
    en: 'Mula',
    ta: 'மூலம்',
    te: 'మూల',
    kn: 'ಮೂಲ',
    hi: 'मूल',
    ml: 'മൂലം',
    bn: 'মূল',
    sa: 'मूल',
  },
  'purva ashadha': {
    en: 'Purva Ashadha',
    ta: 'பூராடம்',
    te: 'పూర్వాషాఢ',
    kn: 'ಪೂರ್ವಾಷಾಢ',
    hi: 'पूर्वाषाढ़ा',
    ml: 'പൂരാടം',
    bn: 'পূর্বাষাঢ়া',
    sa: 'पूर्वाषाढा',
  },
  'uttara ashadha': {
    en: 'Uttara Ashadha',
    ta: 'உத்திராடம்',
    te: 'ఉత్తరాషాఢ',
    kn: 'ಉತ್ತರಾಷಾಢ',
    hi: 'उत्तराषाढ़ा',
    ml: 'ഉത്രാടം',
    bn: 'উত্তরাষাঢ়া',
    sa: 'उत्तराषाढा',
  },
  shravana: {
    en: 'Shravana',
    ta: 'திருவோணம்',
    te: 'శ్రవణం',
    kn: 'ಶ್ರವಣ',
    hi: 'श्रवण',
    ml: 'തിരുവോണം',
    bn: 'শ্রবণা',
    sa: 'श्रवण',
  },
  dhanishta: {
    en: 'Dhanishta',
    ta: 'அவிட்டம்',
    te: 'ధనిష్ఠ',
    kn: 'ಧನಿಷ್ಠಾ',
    hi: 'धनिष्ठा',
    ml: 'അവിട്ടം',
    bn: 'ধনিষ্ঠা',
    sa: 'धनिष्ठा',
  },
  shatabhisha: {
    en: 'Shatabhisha',
    ta: 'சதயம்',
    te: 'శతభిషం',
    kn: 'ಶತಭಿಷಾ',
    hi: 'शतभिषा',
    ml: 'ചതയം',
    bn: 'শতভিষা',
    sa: 'शतभिषा',
  },
  'purva bhadrapada': {
    en: 'Purva Bhadrapada',
    ta: 'பூரட்டாதி',
    te: 'పూర్వాభాద్ర',
    kn: 'ಪೂರ್ವಾಭಾದ್ರ',
    hi: 'पूर्वभाद्रपदा',
    ml: 'പൂരുരുട്ടാതി',
    bn: 'পূর্বভাদ্রপদ',
    sa: 'पूर्वभाद्रपदा',
  },
  'uttara bhadrapada': {
    en: 'Uttara Bhadrapada',
    ta: 'உத்திரட்டாதி',
    te: 'ఉత్తరాభాద్ర',
    kn: 'ಉತ್ತರಾಭಾದ್ರ',
    hi: 'उत्तरभाद्रपदा',
    ml: 'ഉത്രട്ടാതി',
    bn: 'উত্তরভাদ্রপদ',
    sa: 'उत्तरभाद्रपदा',
  },
  revati: {
    en: 'Revati',
    ta: 'ரேவதி',
    te: 'రేవతి',
    kn: 'ರೇವತಿ',
    hi: 'रेवती',
    ml: 'രേവതി',
    bn: 'রেবতী',
    sa: 'रेवती',
  },

  // ===========================================================================
  // 9 Planets (Navagraha)
  // ===========================================================================
  sun: {
    en: 'Sun',
    ta: 'சூரியன்',
    te: 'సూర్యుడు',
    kn: 'ಸೂರ್ಯ',
    hi: 'सूर्य',
    ml: 'സൂര്യന്‍',
    bn: 'সূর্য',
    sa: 'सूर्यः',
  },
  surya: {
    en: 'Surya',
    ta: 'சூரியன்',
    te: 'సూర్యుడు',
    kn: 'ಸೂರ್ಯ',
    hi: 'सूर्य',
    ml: 'സൂര്യന്‍',
    bn: 'সূর্য',
    sa: 'सूर्यः',
  },
  moon: {
    en: 'Moon',
    ta: 'சந்திரன்',
    te: 'చంద్రుడు',
    kn: 'ಚಂದ್ರ',
    hi: 'चन्द्र',
    ml: 'ചന്ദ്രന്‍',
    bn: 'চন্দ্র',
    sa: 'चन्द्रः',
  },
  chandra: {
    en: 'Chandra',
    ta: 'சந்திரன்',
    te: 'చంద్రుడు',
    kn: 'ಚಂದ್ರ',
    hi: 'चन्द्र',
    ml: 'ചന്ദ്രന്‍',
    bn: 'চন্দ্র',
    sa: 'चन्द्रः',
  },
  mars: {
    en: 'Mars',
    ta: 'செவ்வாய்',
    te: 'కుజుడు',
    kn: 'ಮಂಗಳ',
    hi: 'मंगल',
    ml: 'ചൊവ്വ',
    bn: 'মঙ্গল',
    sa: 'मङ्गलः',
  },
  mangal: {
    en: 'Mangal',
    ta: 'செவ்வாய்',
    te: 'కుజుడు',
    kn: 'ಮಂಗಳ',
    hi: 'मंगल',
    ml: 'ചൊവ്വ',
    bn: 'মঙ্গল',
    sa: 'मङ्गलः',
  },
  kuja: {
    en: 'Kuja',
    ta: 'செவ்வாய்',
    te: 'కుజుడు',
    kn: 'ಕುಜ',
    hi: 'कुज',
    ml: 'ചൊവ്വ',
    bn: 'কুজ',
    sa: 'कुजः',
  },
  mercury: {
    en: 'Mercury',
    ta: 'புதன்',
    te: 'బుధుడు',
    kn: 'ಬುಧ',
    hi: 'बुध',
    ml: 'ബുധന്‍',
    bn: 'বুধ',
    sa: 'बुधः',
  },
  budha: {
    en: 'Budha',
    ta: 'புதன்',
    te: 'బుధుడు',
    kn: 'ಬುಧ',
    hi: 'बुध',
    ml: 'ബുധന്‍',
    bn: 'বুধ',
    sa: 'बुधः',
  },
  jupiter: {
    en: 'Jupiter',
    ta: 'குரு',
    te: 'గురువు',
    kn: 'ಗುರು',
    hi: 'गुरु',
    ml: 'വ്യാഴം',
    bn: 'বৃহস্পতি',
    sa: 'बृहस्पतिः',
  },
  guru: {
    en: 'Guru',
    ta: 'குரு',
    te: 'గురువు',
    kn: 'ಗುರು',
    hi: 'गुरु',
    ml: 'വ്യാഴം',
    bn: 'বৃহস্পতি',
    sa: 'बृहस्पतिः',
  },
  brihaspati: {
    en: 'Brihaspati',
    ta: 'குரு',
    te: 'గురువు',
    kn: 'ಬೃಹಸ್ಪತಿ',
    hi: 'बृहस्पति',
    ml: 'വ്യാഴം',
    bn: 'বৃহস্পতি',
    sa: 'बृहस्पतिः',
  },
  venus: {
    en: 'Venus',
    ta: 'சுக்கிரன்',
    te: 'శుక్రుడు',
    kn: 'ಶುಕ್ರ',
    hi: 'शुक्र',
    ml: 'ശുക്രന്‍',
    bn: 'শুক্র',
    sa: 'शुक्रः',
  },
  shukra: {
    en: 'Shukra',
    ta: 'சுக்கிரன்',
    te: 'శుక్రుడు',
    kn: 'ಶುಕ್ರ',
    hi: 'शुक्र',
    ml: 'ശുക്രന്‍',
    bn: 'শুক্র',
    sa: 'शुक्रः',
  },
  saturn: {
    en: 'Saturn',
    ta: 'சனி',
    te: 'శని',
    kn: 'ಶನಿ',
    hi: 'शनि',
    ml: 'ശനി',
    bn: 'শনি',
    sa: 'शनिः',
  },
  shani: {
    en: 'Shani',
    ta: 'சனி',
    te: 'శని',
    kn: 'ಶನಿ',
    hi: 'शनि',
    ml: 'ശനി',
    bn: 'শনি',
    sa: 'शनिः',
  },
  rahu: {
    en: 'Rahu',
    ta: 'ராகு',
    te: 'రాహువు',
    kn: 'ರಾಹು',
    hi: 'राहु',
    ml: 'രാഹു',
    bn: 'রাহু',
    sa: 'राहुः',
  },
  ketu: {
    en: 'Ketu',
    ta: 'கேது',
    te: 'కేతువు',
    kn: 'ಕೇತು',
    hi: 'केतु',
    ml: 'കേതു',
    bn: 'কেতু',
    sa: 'केतुः',
  },

  // ===========================================================================
  // 12 Zodiac Signs (Rashi)
  // ===========================================================================
  aries: {
    en: 'Aries',
    ta: 'மேஷம்',
    te: 'మేషం',
    kn: 'ಮೇಷ',
    hi: 'मेष',
    ml: 'മേടം',
    bn: 'মেষ',
    sa: 'मेषः',
  },
  mesha: {
    en: 'Mesha',
    ta: 'மேஷம்',
    te: 'మేషం',
    kn: 'ಮೇಷ',
    hi: 'मेष',
    ml: 'മേടം',
    bn: 'মেষ',
    sa: 'मेषः',
  },
  taurus: {
    en: 'Taurus',
    ta: 'ரிஷபம்',
    te: 'వృషభం',
    kn: 'ವೃಷಭ',
    hi: 'वृषभ',
    ml: 'ഇടവം',
    bn: 'বৃষ',
    sa: 'वृषभः',
  },
  vrishabha: {
    en: 'Vrishabha',
    ta: 'ரிஷபம்',
    te: 'వృషభం',
    kn: 'ವೃಷಭ',
    hi: 'वृषभ',
    ml: 'ഇടവം',
    bn: 'বৃষ',
    sa: 'वृषभः',
  },
  gemini: {
    en: 'Gemini',
    ta: 'மிதுனம்',
    te: 'మిథునం',
    kn: 'ಮಿಥುನ',
    hi: 'मिथुन',
    ml: 'മിഥുനം',
    bn: 'মিথুন',
    sa: 'मिथुनम्',
  },
  mithuna: {
    en: 'Mithuna',
    ta: 'மிதுனம்',
    te: 'మిథునం',
    kn: 'ಮಿಥುನ',
    hi: 'मिथुन',
    ml: 'മിഥുനം',
    bn: 'মিথুন',
    sa: 'मिथुनम्',
  },
  cancer: {
    en: 'Cancer',
    ta: 'கடகம்',
    te: 'కర్కాటకం',
    kn: 'ಕರ್ಕಾಟಕ',
    hi: 'कर्क',
    ml: 'കര്‍ക്കടകം',
    bn: 'কর্কট',
    sa: 'कर्कटः',
  },
  kataka: {
    en: 'Kataka',
    ta: 'கடகம்',
    te: 'కర్కాటకం',
    kn: 'ಕರ್ಕಾಟಕ',
    hi: 'कर्क',
    ml: 'കര്‍ക്കടകം',
    bn: 'কর্কট',
    sa: 'कर्कटः',
  },
  leo: {
    en: 'Leo',
    ta: 'சிம்மம்',
    te: 'సింహం',
    kn: 'ಸಿಂಹ',
    hi: 'सिंह',
    ml: 'ചിങ്ങം',
    bn: 'সিংহ',
    sa: 'सिंहः',
  },
  simha: {
    en: 'Simha',
    ta: 'சிம்மம்',
    te: 'సింహం',
    kn: 'ಸಿಂಹ',
    hi: 'सिंह',
    ml: 'ചിങ്ങം',
    bn: 'সিংহ',
    sa: 'सिंहः',
  },
  virgo: {
    en: 'Virgo',
    ta: 'கன்னி',
    te: 'కన్య',
    kn: 'ಕನ್ಯಾ',
    hi: 'कन्या',
    ml: 'കന്നി',
    bn: 'কন্যা',
    sa: 'कन्या',
  },
  kanya: {
    en: 'Kanya',
    ta: 'கன்னி',
    te: 'కన్య',
    kn: 'ಕನ್ಯಾ',
    hi: 'कन्या',
    ml: 'കന്നി',
    bn: 'কন্যা',
    sa: 'कन्या',
  },
  libra: {
    en: 'Libra',
    ta: 'துலாம்',
    te: 'తుల',
    kn: 'ತುಲಾ',
    hi: 'तुला',
    ml: 'തുലാം',
    bn: 'তুলা',
    sa: 'तुला',
  },
  tula: {
    en: 'Tula',
    ta: 'துலாம்',
    te: 'తుల',
    kn: 'ತುಲಾ',
    hi: 'तुला',
    ml: 'തുലാം',
    bn: 'তুলা',
    sa: 'तुला',
  },
  scorpio: {
    en: 'Scorpio',
    ta: 'விருச்சிகம்',
    te: 'వృశ్చికం',
    kn: 'ವೃಶ್ಚಿಕ',
    hi: 'वृश्चिक',
    ml: 'വൃശ്ചികം',
    bn: 'বৃশ্চিক',
    sa: 'वृश्चिकः',
  },
  vrischika: {
    en: 'Vrischika',
    ta: 'விருச்சிகம்',
    te: 'వృశ్చికం',
    kn: 'ವೃಶ್ಚಿಕ',
    hi: 'वृश्चिक',
    ml: 'വൃശ്ചികം',
    bn: 'বৃশ্চিক',
    sa: 'वृश्चिकः',
  },
  sagittarius: {
    en: 'Sagittarius',
    ta: 'தனுசு',
    te: 'ధనుస్సు',
    kn: 'ಧನು',
    hi: 'धनु',
    ml: 'ധനു',
    bn: 'ধনু',
    sa: 'धनुः',
  },
  dhanus: {
    en: 'Dhanus',
    ta: 'தனுசு',
    te: 'ధనుస్సు',
    kn: 'ಧನು',
    hi: 'धनु',
    ml: 'ധനു',
    bn: 'ধনু',
    sa: 'धनुः',
  },
  capricorn: {
    en: 'Capricorn',
    ta: 'மகரம்',
    te: 'మకరం',
    kn: 'ಮಕರ',
    hi: 'मकर',
    ml: 'മകരം',
    bn: 'মকর',
    sa: 'मकरः',
  },
  makara: {
    en: 'Makara',
    ta: 'மகரம்',
    te: 'మకరం',
    kn: 'ಮಕರ',
    hi: 'मकर',
    ml: 'മകരം',
    bn: 'মকর',
    sa: 'मकरः',
  },
  aquarius: {
    en: 'Aquarius',
    ta: 'கும்பம்',
    te: 'కుంభం',
    kn: 'ಕುಂಭ',
    hi: 'कुम्भ',
    ml: 'കുംഭം',
    bn: 'কুম্ভ',
    sa: 'कुम्भः',
  },
  kumbha: {
    en: 'Kumbha',
    ta: 'கும்பம்',
    te: 'కుంభం',
    kn: 'ಕುಂಭ',
    hi: 'कुम्भ',
    ml: 'കുംഭം',
    bn: 'কুম্ভ',
    sa: 'कुम्भः',
  },
  pisces: {
    en: 'Pisces',
    ta: 'மீனம்',
    te: 'మీనం',
    kn: 'ಮೀನ',
    hi: 'मीन',
    ml: 'മീനം',
    bn: 'মীন',
    sa: 'मीनः',
  },
  meena: {
    en: 'Meena',
    ta: 'மீனம்',
    te: 'మీనం',
    kn: 'ಮೀನ',
    hi: 'मीन',
    ml: 'മീനം',
    bn: 'মীন',
    sa: 'मीनः',
  },

  // ===========================================================================
  // 7 Weekdays (Vara)
  // ===========================================================================
  sunday: {
    en: 'Sunday',
    ta: 'ஞாயிறு',
    te: 'ఆదివారం',
    kn: 'ಭಾನುವಾರ',
    hi: 'रविवार',
    ml: 'ഞായര്‍',
    bn: 'রবিবার',
    sa: 'रविवारः',
  },
  ravivara: {
    en: 'Ravivara',
    ta: 'ஞாயிறு',
    te: 'ఆదివారం',
    kn: 'ಭಾನುವಾರ',
    hi: 'रविवार',
    ml: 'ഞായര്‍',
    bn: 'রবিবার',
    sa: 'रविवारः',
  },
  monday: {
    en: 'Monday',
    ta: 'திங்கள்',
    te: 'సోమవారం',
    kn: 'ಸೋಮವಾರ',
    hi: 'सोमवार',
    ml: 'തിങ്കള്‍',
    bn: 'সোমবার',
    sa: 'सोमवारः',
  },
  somavara: {
    en: 'Somavara',
    ta: 'திங்கள்',
    te: 'సోమవారం',
    kn: 'ಸೋಮವಾರ',
    hi: 'सोमवार',
    ml: 'തിങ്കള്‍',
    bn: 'সোমবার',
    sa: 'सोमवारः',
  },
  tuesday: {
    en: 'Tuesday',
    ta: 'செவ்வாய்',
    te: 'మంగళవారం',
    kn: 'ಮಂಗಳವಾರ',
    hi: 'मंगलवार',
    ml: 'ചൊവ്വ',
    bn: 'মঙ্গলবার',
    sa: 'मङ्गलवारः',
  },
  mangalavara: {
    en: 'Mangalavara',
    ta: 'செவ்வாய்',
    te: 'మంగళవారం',
    kn: 'ಮಂಗಳವಾರ',
    hi: 'मंगलवार',
    ml: 'ചൊവ്വ',
    bn: 'মঙ্গলবার',
    sa: 'मङ्गलवारः',
  },
  wednesday: {
    en: 'Wednesday',
    ta: 'புதன்',
    te: 'బుధవారం',
    kn: 'ಬುಧವಾರ',
    hi: 'बुधवार',
    ml: 'ബുധന്‍',
    bn: 'বুধবার',
    sa: 'बुधवारः',
  },
  budhavara: {
    en: 'Budhavara',
    ta: 'புதன்',
    te: 'బుధవారం',
    kn: 'ಬುಧವಾರ',
    hi: 'बुधवार',
    ml: 'ബുധന്‍',
    bn: 'বুধবার',
    sa: 'बुधवारः',
  },
  thursday: {
    en: 'Thursday',
    ta: 'வியாழன்',
    te: 'గురువారం',
    kn: 'ಗುರುವಾರ',
    hi: 'गुरुवार',
    ml: 'വ്യാഴം',
    bn: 'বৃহস্পতিবার',
    sa: 'गुरुवारः',
  },
  guruvara: {
    en: 'Guruvara',
    ta: 'வியாழன்',
    te: 'గురువారం',
    kn: 'ಗುರುವಾರ',
    hi: 'गुरुवार',
    ml: 'വ്യാഴം',
    bn: 'বৃহস্পতিবার',
    sa: 'गुरुवारः',
  },
  friday: {
    en: 'Friday',
    ta: 'வெள்ளி',
    te: 'శుక్రవారం',
    kn: 'ಶುಕ್ರವಾರ',
    hi: 'शुक्रवार',
    ml: 'വെള്ളി',
    bn: 'শুক্রবার',
    sa: 'शुक्रवारः',
  },
  shukravara: {
    en: 'Shukravara',
    ta: 'வெள்ளி',
    te: 'శుక్రవారం',
    kn: 'ಶುಕ್ರವಾರ',
    hi: 'शुक्रवार',
    ml: 'വെള്ളി',
    bn: 'শুক্রবার',
    sa: 'शुक्रवारः',
  },
  saturday: {
    en: 'Saturday',
    ta: 'சனி',
    te: 'శనివారం',
    kn: 'ಶನಿವಾರ',
    hi: 'शनिवार',
    ml: 'ശനി',
    bn: 'শনিবার',
    sa: 'शनिवारः',
  },
  shanivara: {
    en: 'Shanivara',
    ta: 'சனி',
    te: 'శనివారం',
    kn: 'ಶನಿವಾರ',
    hi: 'शनिवार',
    ml: 'ശനി',
    bn: 'শনিবার',
    sa: 'शनिवारः',
  },

  // ===========================================================================
  // 15+1 Tithis (including Amavasya)
  // ===========================================================================
  pratipada: {
    en: 'Pratipada',
    ta: 'பிரதமை',
    te: 'పాడ్యమి',
    kn: 'ಪಾಡ್ಯ',
    hi: 'प्रतिपदा',
    ml: 'പ്രഥമ',
    bn: 'প্রতিপদ',
    sa: 'प्रतिपदा',
  },
  dwitiya: {
    en: 'Dwitiya',
    ta: 'துவிதியை',
    te: 'విదియ',
    kn: 'ಬಿದಿಗೆ',
    hi: 'द्वितीया',
    ml: 'ദ്വിതീയ',
    bn: 'দ্বিতীয়া',
    sa: 'द्वितीया',
  },
  tritiya: {
    en: 'Tritiya',
    ta: 'திருதியை',
    te: 'తదియ',
    kn: 'ತದಿಗೆ',
    hi: 'तृतीया',
    ml: 'തൃതീയ',
    bn: 'তৃতীয়া',
    sa: 'तृतीया',
  },
  chaturthi: {
    en: 'Chaturthi',
    ta: 'சதுர்த்தி',
    te: 'చవితి',
    kn: 'ಚತುರ್ಥಿ',
    hi: 'चतुर्थी',
    ml: 'ചതുര്‍ത്ഥി',
    bn: 'চতুর্থী',
    sa: 'चतुर्थी',
  },
  panchami: {
    en: 'Panchami',
    ta: 'பஞ்சமி',
    te: 'పంచమి',
    kn: 'ಪಂಚಮಿ',
    hi: 'पंचमी',
    ml: 'പഞ്ചമി',
    bn: 'পঞ্চমী',
    sa: 'पञ्चमी',
  },
  shashthi: {
    en: 'Shashthi',
    ta: 'சஷ்டி',
    te: 'షష్ఠి',
    kn: 'ಷಷ್ಠಿ',
    hi: 'षष्ठी',
    ml: 'ഷഷ്ഠി',
    bn: 'ষষ্ঠী',
    sa: 'षष्ठी',
  },
  saptami: {
    en: 'Saptami',
    ta: 'சப்தமி',
    te: 'సప్తమి',
    kn: 'ಸಪ್ತಮಿ',
    hi: 'सप्तमी',
    ml: 'സപ്തമി',
    bn: 'সপ্তমী',
    sa: 'सप्तमी',
  },
  ashtami: {
    en: 'Ashtami',
    ta: 'அஷ்டமி',
    te: 'అష్టమి',
    kn: 'ಅಷ್ಟಮಿ',
    hi: 'अष्टमी',
    ml: 'അഷ്ടമി',
    bn: 'অষ্টমী',
    sa: 'अष्टमी',
  },
  navami: {
    en: 'Navami',
    ta: 'நவமி',
    te: 'నవమి',
    kn: 'ನವಮಿ',
    hi: 'नवमी',
    ml: 'നവമി',
    bn: 'নবমী',
    sa: 'नवमी',
  },
  dashami: {
    en: 'Dashami',
    ta: 'தசமி',
    te: 'దశమి',
    kn: 'ದಶಮಿ',
    hi: 'दशमी',
    ml: 'ദശമി',
    bn: 'দশমী',
    sa: 'दशमी',
  },
  ekadashi: {
    en: 'Ekadashi',
    ta: 'ஏகாதசி',
    te: 'ఏకాదశి',
    kn: 'ಏಕಾದಶಿ',
    hi: 'एकादशी',
    ml: 'ഏകാദശി',
    bn: 'একাদশী',
    sa: 'एकादशी',
  },
  dwadashi: {
    en: 'Dwadashi',
    ta: 'துவாதசி',
    te: 'ద్వాదశి',
    kn: 'ದ್ವಾದಶಿ',
    hi: 'द्वादशी',
    ml: 'ദ്വാദശി',
    bn: 'দ্বাদশী',
    sa: 'द्वादशी',
  },
  trayodashi: {
    en: 'Trayodashi',
    ta: 'திரயோதசி',
    te: 'త్రయోదశి',
    kn: 'ತ್ರಯೋದಶಿ',
    hi: 'त्रयोदशी',
    ml: 'ത്രയോദശി',
    bn: 'ত্রয়োদশী',
    sa: 'त्रयोदशी',
  },
  chaturdashi: {
    en: 'Chaturdashi',
    ta: 'சதுர்தசி',
    te: 'చతుర్దశి',
    kn: 'ಚತುರ್ದಶಿ',
    hi: 'चतुर्दशी',
    ml: 'ചതുര്‍ദ്ദശി',
    bn: 'চতুর্দশী',
    sa: 'चतुर्दशी',
  },
  purnima: {
    en: 'Purnima',
    ta: 'பௌர்ணமி',
    te: 'పౌర్ణమి',
    kn: 'ಹುಣ್ಣಿಮೆ',
    hi: 'पूर्णिमा',
    ml: 'പൗര്‍ണ്ണമി',
    bn: 'পূর্ণিমা',
    sa: 'पूर्णिमा',
  },
  amavasya: {
    en: 'Amavasya',
    ta: 'அமாவாசை',
    te: 'అమావాస్య',
    kn: 'ಅಮಾವಾಸ್ಯೆ',
    hi: 'अमावस्या',
    ml: 'അമാവാസി',
    bn: 'অমাবস্যা',
    sa: 'अमावास्या',
  },

  // ===========================================================================
  // 27 Yogas
  // ===========================================================================
  vishkambha: {
    en: 'Vishkambha',
    ta: 'விஷ்கம்பம்',
    te: 'విష్కంభం',
    kn: 'ವಿಷ್ಕಂಭ',
    hi: 'विष्कम्भ',
    ml: 'വിഷ്കംഭം',
    bn: 'বিষ্কম্ভ',
    sa: 'विष्कम्भः',
  },
  preeti: {
    en: 'Preeti',
    ta: 'ப்ரீதி',
    te: 'ప్రీతి',
    kn: 'ಪ್ರೀತಿ',
    hi: 'प्रीति',
    ml: 'പ്രീതി',
    bn: 'প্রীতি',
    sa: 'प्रीतिः',
  },
  ayushman: {
    en: 'Ayushman',
    ta: 'ஆயுஷ்மான்',
    te: 'ఆయుష్మాన్',
    kn: 'ಆಯುಷ್ಮಾನ್',
    hi: 'आयुष्मान्',
    ml: 'ആയുഷ്മാന്‍',
    bn: 'আয়ুষ্মান',
    sa: 'आयुष्मान्',
  },
  saubhagya: {
    en: 'Saubhagya',
    ta: 'சௌபாக்கியம்',
    te: 'సౌభాగ్యం',
    kn: 'ಸೌಭಾಗ್ಯ',
    hi: 'सौभाग्य',
    ml: 'സൗഭാഗ്യം',
    bn: 'সৌভাগ্য',
    sa: 'सौभाग्यम्',
  },
  shobhana: {
    en: 'Shobhana',
    ta: 'சோபனம்',
    te: 'శోభనం',
    kn: 'ಶೋಭನ',
    hi: 'शोभन',
    ml: 'ശോഭനം',
    bn: 'শোভন',
    sa: 'शोभनम्',
  },
  atiganda: {
    en: 'Atiganda',
    ta: 'அதிகண்டம்',
    te: 'అతిగండం',
    kn: 'ಅತಿಗಂಡ',
    hi: 'अतिगण्ड',
    ml: 'അതിഗണ്ഡം',
    bn: 'অতিগণ্ড',
    sa: 'अतिगण्डः',
  },
  sukarma: {
    en: 'Sukarma',
    ta: 'சுகர்மா',
    te: 'సుకర్మ',
    kn: 'ಸುಕರ್ಮ',
    hi: 'सुकर्मा',
    ml: 'സുകര്‍മ്മ',
    bn: 'সুকর্মা',
    sa: 'सुकर्मा',
  },
  dhriti: {
    en: 'Dhriti',
    ta: 'திருதி',
    te: 'ధృతి',
    kn: 'ಧೃತಿ',
    hi: 'धृति',
    ml: 'ധൃതി',
    bn: 'ধৃতি',
    sa: 'धृतिः',
  },
  shoola: {
    en: 'Shoola',
    ta: 'சூலம்',
    te: 'శూలం',
    kn: 'ಶೂಲ',
    hi: 'शूल',
    ml: 'ശൂലം',
    bn: 'শূল',
    sa: 'शूलम्',
  },
  ganda: {
    en: 'Ganda',
    ta: 'கண்டம்',
    te: 'గండం',
    kn: 'ಗಂಡ',
    hi: 'गण्ड',
    ml: 'ഗണ്ഡം',
    bn: 'গণ্ড',
    sa: 'गण्डः',
  },
  vriddhi: {
    en: 'Vriddhi',
    ta: 'விருத்தி',
    te: 'వృద్ధి',
    kn: 'ವೃದ್ಧಿ',
    hi: 'वृद्धि',
    ml: 'വൃദ്ധി',
    bn: 'বৃদ্ধি',
    sa: 'वृद्धिः',
  },
  dhruva: {
    en: 'Dhruva',
    ta: 'துருவம்',
    te: 'ధ్రువం',
    kn: 'ಧ್ರುವ',
    hi: 'ध्रुव',
    ml: 'ധ്രുവം',
    bn: 'ধ্রুব',
    sa: 'ध्रुवः',
  },
  vyaghata: {
    en: 'Vyaghata',
    ta: 'வியாகாதம்',
    te: 'వ్యాఘాతం',
    kn: 'ವ್ಯಾಘಾತ',
    hi: 'व्याघात',
    ml: 'വ്യാഘാതം',
    bn: 'ব্যাঘাত',
    sa: 'व्याघातः',
  },
  harshana: {
    en: 'Harshana',
    ta: 'ஹர்ஷணம்',
    te: 'హర్షణం',
    kn: 'ಹರ್ಷಣ',
    hi: 'हर्षण',
    ml: 'ഹര്‍ഷണം',
    bn: 'হর্ষণ',
    sa: 'हर्षणम्',
  },
  vajra: {
    en: 'Vajra',
    ta: 'வஜ்ரம்',
    te: 'వజ్రం',
    kn: 'ವಜ್ರ',
    hi: 'वज्र',
    ml: 'വജ്രം',
    bn: 'বজ্র',
    sa: 'वज्रम्',
  },
  siddhi: {
    en: 'Siddhi',
    ta: 'சித்தி',
    te: 'సిద్ధి',
    kn: 'ಸಿದ್ಧಿ',
    hi: 'सिद्धि',
    ml: 'സിദ്ധി',
    bn: 'সিদ্ধি',
    sa: 'सिद्धिः',
  },
  vyatipata: {
    en: 'Vyatipata',
    ta: 'வியதீபாதம்',
    te: 'వ్యతీపాతం',
    kn: 'ವ್ಯತೀಪಾತ',
    hi: 'व्यतीपात',
    ml: 'വ്യതീപാതം',
    bn: 'ব্যতীপাত',
    sa: 'व्यतीपातः',
  },
  variyan: {
    en: 'Variyan',
    ta: 'வரீயான்',
    te: 'వరీయాన్',
    kn: 'ವರೀಯಾನ್',
    hi: 'वरीयान्',
    ml: 'വരീയാന്‍',
    bn: 'বরীয়ান',
    sa: 'वरीयान्',
  },
  parigha: {
    en: 'Parigha',
    ta: 'பரிகம்',
    te: 'పరిఘం',
    kn: 'ಪರಿಘ',
    hi: 'परिघ',
    ml: 'പരിഘം',
    bn: 'পরিঘ',
    sa: 'परिघः',
  },
  shiva: {
    en: 'Shiva',
    ta: 'சிவம்',
    te: 'శివం',
    kn: 'ಶಿವ',
    hi: 'शिव',
    ml: 'ശിവം',
    bn: 'শিব',
    sa: 'शिवः',
  },
  siddha: {
    en: 'Siddha',
    ta: 'சித்தம்',
    te: 'సిద్ధం',
    kn: 'ಸಿದ್ಧ',
    hi: 'सिद्ध',
    ml: 'സിദ്ധം',
    bn: 'সিদ্ধ',
    sa: 'सिद्धः',
  },
  sadhya: {
    en: 'Sadhya',
    ta: 'சாத்தியம்',
    te: 'సాధ్యం',
    kn: 'ಸಾಧ್ಯ',
    hi: 'साध्य',
    ml: 'സാധ്യം',
    bn: 'সাধ্য',
    sa: 'साध्यः',
  },
  shubha: {
    en: 'Shubha',
    ta: 'சுபம்',
    te: 'శుభం',
    kn: 'ಶುಭ',
    hi: 'शुभ',
    ml: 'ശുഭം',
    bn: 'শুভ',
    sa: 'शुभः',
  },
  shukla: {
    en: 'Shukla',
    ta: 'சுக்லம்',
    te: 'శుక్లం',
    kn: 'ಶುಕ್ಲ',
    hi: 'शुक्ल',
    ml: 'ശുക്ലം',
    bn: 'শুক্ল',
    sa: 'शुक्लः',
  },
  brahma: {
    en: 'Brahma',
    ta: 'பிரம்மா',
    te: 'బ్రహ్మ',
    kn: 'ಬ್ರಹ್ಮ',
    hi: 'ब्रह्म',
    ml: 'ബ്രഹ്മ',
    bn: 'ব্রহ্ম',
    sa: 'ब्रह्मा',
  },
  indra: {
    en: 'Indra',
    ta: 'இந்திரன்',
    te: 'ఇంద్ర',
    kn: 'ಇಂದ್ರ',
    hi: 'इन्द्र',
    ml: 'ഇന്ദ്രന്‍',
    bn: 'ইন্দ্র',
    sa: 'इन्द्रः',
  },
  vaidhriti: {
    en: 'Vaidhriti',
    ta: 'வைத்ருதி',
    te: 'వైధృతి',
    kn: 'ವೈಧೃತಿ',
    hi: 'वैधृति',
    ml: 'വൈധൃതി',
    bn: 'বৈধৃতি',
    sa: 'वैधृतिः',
  },

  // ===========================================================================
  // 11 Karanas
  // ===========================================================================
  bava: {
    en: 'Bava',
    ta: 'பவம்',
    te: 'బవ',
    kn: 'ಬವ',
    hi: 'बव',
    ml: 'ബവം',
    bn: 'বব',
    sa: 'बवः',
  },
  balava: {
    en: 'Balava',
    ta: 'பாலவம்',
    te: 'బాలవ',
    kn: 'ಬಾಲವ',
    hi: 'बालव',
    ml: 'ബാലവം',
    bn: 'বালব',
    sa: 'बालवः',
  },
  kaulava: {
    en: 'Kaulava',
    ta: 'கௌலவம்',
    te: 'కౌలవ',
    kn: 'ಕೌಲವ',
    hi: 'कौलव',
    ml: 'കൗലവം',
    bn: 'কৌলব',
    sa: 'कौलवः',
  },
  taitila: {
    en: 'Taitila',
    ta: 'தைதுலம்',
    te: 'తైతిల',
    kn: 'ತೈತಿಲ',
    hi: 'तैतिल',
    ml: 'തൈതിലം',
    bn: 'তৈতিল',
    sa: 'तैतिलः',
  },
  gara: {
    en: 'Gara',
    ta: 'கரம்',
    te: 'గర',
    kn: 'ಗರ',
    hi: 'गर',
    ml: 'ഗരം',
    bn: 'গর',
    sa: 'गरः',
  },
  vanija: {
    en: 'Vanija',
    ta: 'வணிஜம்',
    te: 'వణిజ',
    kn: 'ವಣಿಜ',
    hi: 'वणिज',
    ml: 'വണിജം',
    bn: 'বণিজ',
    sa: 'वणिजः',
  },
  vishti: {
    en: 'Vishti',
    ta: 'பத்ரை',
    te: 'భద్ర',
    kn: 'ಭದ್ರೆ',
    hi: 'विष्टि',
    ml: 'ഭദ്ര',
    bn: 'বিষ্টি',
    sa: 'विष्टिः',
  },
  shakuni: {
    en: 'Shakuni',
    ta: 'சகுனி',
    te: 'శకుని',
    kn: 'ಶಕುನಿ',
    hi: 'शकुनि',
    ml: 'ശകുനി',
    bn: 'শকুনি',
    sa: 'शकुनिः',
  },
  chatushpada: {
    en: 'Chatushpada',
    ta: 'சதுஷ்பாதம்',
    te: 'చతుష్పాదం',
    kn: 'ಚತುಷ್ಪಾದ',
    hi: 'चतुष्पद',
    ml: 'ചതുഷ്പാദം',
    bn: 'চতুষ্পদ',
    sa: 'चतुष्पदः',
  },
  naga: {
    en: 'Naga',
    ta: 'நாகம்',
    te: 'నాగం',
    kn: 'ನಾಗ',
    hi: 'नाग',
    ml: 'നാഗം',
    bn: 'নাগ',
    sa: 'नागः',
  },
  kimstughna: {
    en: 'Kimstughna',
    ta: 'கிம்ஸ்துக்னம்',
    te: 'కింస్తుఘ్నం',
    kn: 'ಕಿಂಸ್ತುಘ್ನ',
    hi: 'किंस्तुघ्न',
    ml: 'കിംസ്തുഘ്നം',
    bn: 'কিংস্তুঘ্ন',
    sa: 'किंस्तुघ्नः',
  },

  // ===========================================================================
  // Miscellaneous Astrological Terms
  // ===========================================================================
  'rahu kaal': {
    en: 'Rahu Kaal',
    ta: 'ராகு காலம்',
    te: 'రాహు కాలం',
    kn: 'ರಾಹು ಕಾಲ',
    hi: 'राहु काल',
    ml: 'രാഹു കാലം',
    bn: 'রাহু কাল',
    sa: 'राहुकालः',
  },
  'rahu kalam': {
    en: 'Rahu Kalam',
    ta: 'ராகு காலம்',
    te: 'రాహు కాలం',
    kn: 'ರಾಹು ಕಾಲ',
    hi: 'राहु काल',
    ml: 'രാഹു കാലം',
    bn: 'রাহু কাল',
    sa: 'राहुकालः',
  },
  'gulika kaal': {
    en: 'Gulika Kaal',
    ta: 'குளிகை காலம்',
    te: 'గుళిక కాలం',
    kn: 'ಗುಳಿಕ ಕಾಲ',
    hi: 'गुलिक काल',
    ml: 'ഗുളിക കാലം',
    bn: 'গুলিক কাল',
    sa: 'गुलिककालः',
  },
  yamaganda: {
    en: 'Yamaganda',
    ta: 'எமகண்டம்',
    te: 'యమగండం',
    kn: 'ಯಮಗಂಡ',
    hi: 'यमगण्ड',
    ml: 'യമകണ്ഡം',
    bn: 'যমগণ্ড',
    sa: 'यमगण्डः',
  },
  'abhijit muhurta': {
    en: 'Abhijit Muhurta',
    ta: 'அபிஜித் முகூர்த்தம்',
    te: 'అభిజిత్ ముహూర్తం',
    kn: 'ಅಭಿಜಿತ್ ಮುಹೂರ್ತ',
    hi: 'अभिजित् मुहूर्त',
    ml: 'അഭിജിത് മുഹൂര്‍ത്തം',
    bn: 'অভিজিৎ মুহূর্ত',
    sa: 'अभिजिन्मुहूर्तः',
  },
  'brahma muhurta': {
    en: 'Brahma Muhurta',
    ta: 'பிரம்ம முகூர்த்தம்',
    te: 'బ్రహ్మ ముహూర్తం',
    kn: 'ಬ್ರಹ್ಮ ಮುಹೂರ್ತ',
    hi: 'ब्रह्म मुहूर्त',
    ml: 'ബ്രഹ്മ മുഹൂര്‍ത്തം',
    bn: 'ব্রহ্ম মুহূর্ত',
    sa: 'ब्रह्ममुहूर्तः',
  },
  panchang: {
    en: 'Panchang',
    ta: 'பஞ்சாங்கம்',
    te: 'పంచాంగం',
    kn: 'ಪಂಚಾಂಗ',
    hi: 'पंचांग',
    ml: 'പഞ്ചാംഗം',
    bn: 'পঞ্চাঙ্গ',
    sa: 'पञ्चाङ्गम्',
  },
  muhurta: {
    en: 'Muhurta',
    ta: 'முகூர்த்தம்',
    te: 'ముహూర్తం',
    kn: 'ಮುಹೂರ್ತ',
    hi: 'मुहूर्त',
    ml: 'മുഹൂര്‍ത്തം',
    bn: 'মুহূর্ত',
    sa: 'मुहूर्तः',
  },
  dasha: {
    en: 'Dasha',
    ta: 'தசை',
    te: 'దశ',
    kn: 'ದಶಾ',
    hi: 'दशा',
    ml: 'ദശ',
    bn: 'দশা',
    sa: 'दशा',
  },
  mahadasha: {
    en: 'Mahadasha',
    ta: 'மகாதசை',
    te: 'మహాదశ',
    kn: 'ಮಹಾದಶಾ',
    hi: 'महादशा',
    ml: 'മഹാദശ',
    bn: 'মহাদশা',
    sa: 'महादशा',
  },
  antardasha: {
    en: 'Antardasha',
    ta: 'அந்தர்தசை',
    te: 'అంతర్దశ',
    kn: 'ಅಂತರ್ದಶಾ',
    hi: 'अन्तर्दशा',
    ml: 'അന്തര്‍ദശ',
    bn: 'অন্তর্দশা',
    sa: 'अन्तर्दशा',
  },
  ayanamsa: {
    en: 'Ayanamsa',
    ta: 'அயனாம்சம்',
    te: 'అయనాంశం',
    kn: 'ಅಯನಾಂಶ',
    hi: 'अयनांश',
    ml: 'അയനാംശം',
    bn: 'অয়নাংশ',
    sa: 'अयनांशः',
  },
  lagna: {
    en: 'Lagna',
    ta: 'லக்னம்',
    te: 'లగ్నం',
    kn: 'ಲಗ್ನ',
    hi: 'लग्न',
    ml: 'ലഗ്നം',
    bn: 'লগ্ন',
    sa: 'लग्नम्',
  },
  ascendant: {
    en: 'Ascendant',
    ta: 'லக்னம்',
    te: 'లగ్నం',
    kn: 'ಲಗ್ನ',
    hi: 'लग्न',
    ml: 'ലഗ്നം',
    bn: 'লগ্ন',
    sa: 'लग्नम्',
  },
  rashi: {
    en: 'Rashi',
    ta: 'ராசி',
    te: 'రాశి',
    kn: 'ರಾಶಿ',
    hi: 'राशि',
    ml: 'രാശി',
    bn: 'রাশি',
    sa: 'राशिः',
  },
  nakshatra: {
    en: 'Nakshatra',
    ta: 'நட்சத்திரம்',
    te: 'నక్షత్రం',
    kn: 'ನಕ್ಷತ್ರ',
    hi: 'नक्षत्र',
    ml: 'നക്ഷത്രം',
    bn: 'নক্ষত্র',
    sa: 'नक्षत्रम्',
  },
  tithi: {
    en: 'Tithi',
    ta: 'திதி',
    te: 'తిథి',
    kn: 'ತಿಥಿ',
    hi: 'तिथि',
    ml: 'തിഥി',
    bn: 'তিথি',
    sa: 'तिथिः',
  },
  yoga: {
    en: 'Yoga',
    ta: 'யோகம்',
    te: 'యోగం',
    kn: 'ಯೋಗ',
    hi: 'योग',
    ml: 'യോഗം',
    bn: 'যোগ',
    sa: 'योगः',
  },
  karana: {
    en: 'Karana',
    ta: 'கரணம்',
    te: 'కరణం',
    kn: 'ಕರಣ',
    hi: 'करण',
    ml: 'കരണം',
    bn: 'করণ',
    sa: 'करणम्',
  },
  vara: {
    en: 'Vara',
    ta: 'வாரம்',
    te: 'వారం',
    kn: 'ವಾರ',
    hi: 'वार',
    ml: 'വാരം',
    bn: 'বার',
    sa: 'वारः',
  },

  // ===========================================================================
  // Paksha (lunar phase halves — used in tithi display)
  // ===========================================================================
  krishna: {
    en: 'Krishna',
    ta: 'கிருஷ்ண',
    te: 'కృష్ణ',
    kn: 'ಕೃಷ್ಣ',
    hi: 'कृष्ण',
    ml: 'കൃഷ്ണ',
    bn: 'কৃষ্ণ',
    sa: 'कृष्णः',
  },
  shukla_paksha: {
    en: 'Shukla Paksha',
    ta: 'சுக்ல பட்சம்',
    te: 'శుక్ల పక్షం',
    kn: 'ಶುಕ್ಲ ಪಕ್ಷ',
    hi: 'शुक्ल पक्ष',
    ml: 'ശുക്ല പക്ഷം',
    bn: 'শুক্ল পক্ষ',
    sa: 'शुक्लपक्षः',
  },
  krishna_paksha: {
    en: 'Krishna Paksha',
    ta: 'கிருஷ்ண பட்சம்',
    te: 'కృష్ణ పక్షం',
    kn: 'ಕೃಷ್ಣ ಪಕ್ಷ',
    hi: 'कृष्ण पक्ष',
    ml: 'കൃഷ്ണ പക്ഷം',
    bn: 'কৃষ্ণ পক্ষ',
    sa: 'कृष्णपक्षः',
  },
};

/**
 * Reverse-index: English display names (case-insensitive) to glossary keys.
 * Built lazily on first access so there is no startup cost if unused.
 */
let _englishIndex: Map<string, string> | null = null;

function getEnglishIndex(): Map<string, string> {
  if (!_englishIndex) {
    _englishIndex = new Map();
    for (const [key, entry] of Object.entries(GLOSSARY)) {
      _englishIndex.set(entry.en.toLowerCase(), key);
    }
  }
  return _englishIndex;
}

/**
 * Look up a glossary entry by its English display name (case-insensitive).
 * Falls back to a direct key lookup.
 */
export function findEntry(term: string): GlossaryEntry | undefined {
  const lower = term.toLowerCase();
  // Direct key match first (most terms are keyed by lowercase English)
  if (GLOSSARY[lower]) return GLOSSARY[lower];
  // Reverse index by English name
  const key = getEnglishIndex().get(lower);
  return key ? GLOSSARY[key] : undefined;
}
